# This is a basic workflow to help you get started with Actions

name: deploy GAS

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the develop branch
  pull_request:
    branches:
      - develop
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This job only run on pull request was merged
jobs:
  if_merged:
    if: |
      (github.event.pull_request.merged == true) &&
        contains(github.event.pull_request.labels.*.name, 'GAS')
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      # https://dev.classmethod.jp/articles/github-actions-gas-deploy/
      - name: Install Clasp
        run: |
          npm init -y
          npm install clasp -g
      - name: Create clasprc.json
        run: |
          echo \{\"token\":\{\"access_token\":\"${{ secrets.CLASP_ACCESS_TOKEN}}\",\"scope\":\"https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/logging.read openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/cloud-platform\",\"token_type\":\"Bearer\",\"id_token\":\"${{ secrets.CLASP_ID_TOKEN }}\",\"expiry_date\":1620870307822,\"refresh_token\":\"${{ secrets.CLASP_REFRESH_TOKEN }}\"\},\"oauth2ClientSettings\":\{\"clientId\":\"${{ secrets.CLASP_CLIENTID }}\",\"clientSecret\":\"${{ secrets.CLASP_CLIENTSECRET }}\",\"redirectUri\":\"http://localhost\"\},\"isLocalCreds\":false\} > ~/.clasprc.json
      - name: Create .clasp.json
        run: |
          echo \{\"scriptId\":\"${{ secrets.GAS_SCRIPT_ID }}\",\"rootDir\":\"/home/runner/work/mynews/mynews/src\"\} > ./.clasp.json
      - name: Deploy
        run: |
          clasp deploy --deploymentId ${{ secrets.CLASP_PROD_DEPLOYMENT_ID }} --description "本番環境"
