# This is a basic workflow to help you get started with Actions

name: deploy Cloud Functions

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the develop branch
  pull_request:
    branches:
      - develop
      - 16-auto-deploy-cloud-functions
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This job only run on pull request was merged
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      # https://dev.classmethod.jp/articles/caching-dependencies-in-workflow-execution-on-github-actions/
      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm install

      # https://github.com/marketplace/actions/github-action-for-firebase
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.1.2
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
